import pandas as pd
from datetime import datetime
import tensorflow as tf
import random
import sklearn
import numpy as np

start=datetime.now()

df = pd.read_csv('New folder/processed-dataset/cicdos2019-multi-test.csv')

#df['Max Packet Length'] = df['Max Packet Length'].astype(float)
#df['Protocol'] = df['Protocol'].astype(float)
#df['Fwd Packet Length Std'] = df['Fwd Packet Length Std'].astype(float)
#df['Bwd Packet Length Min'] = df['Bwd Packet Length Min'].astype(float)
#df['Fwd Packet Length Max'] = df['Fwd Packet Length Max'].astype(float)
#df['Bwd IAT Total'] = df['Bwd IAT Total'].astype(float)
#df['Bwd IAT Min'] = df['Bwd IAT Min'].astype(float)
#df['Bwd Packets/s'] = df['Bwd Packets/s'].astype(float)
#df['ACK Flag Count'] = df['ACK Flag Count'].astype(float)
#df['Down/Up Ratio'] = df['Down/Up Ratio'].astype(float)
#df['Init_Win_bytes_forward'] = df['Init_Win_bytes_forward'].astype(float)
#df['Init_Win_bytes_backward'] = df['Init_Win_bytes_backward'].astype(float)
#df['act_data_pkt_fwd'] = df['act_data_pkt_fwd'].astype(float)
#df['Flow Bytes/s'] = df['Flow Bytes/s'].astype(float)
#df['Bwd Header Length'] = df['Bwd Header Length'].astype(float)
#df['Packet Length Variance'] = df['Packet Length Variance'].astype(float)
#df['SYN Flag Count'] = df['SYN Flag Count'].astype(float)
#df['URG Flag Count'] = df['URG Flag Count'].astype(float)
#df['CWE Flag Count'] = df['CWE Flag Count'].astype(float)
#df['Active Std'] = df['Active Std'].astype(float)
#df['Active Max'] = df['Active Max'].astype(float)
#df['Idle Std'] = df['Idle Std'].astype(float)

df = df.drop('Subflow Fwd Bytes', axis=1)
df = df.drop('Min Packet Length', axis=1)
df = df.drop('Fwd Packets/s', axis=1)
df = df.drop('Fwd Header Length', axis=1)
df = df.drop('Flow IAT Max', axis=1)
df = df.drop('Fwd IAT Mean', axis=1)
df = df.drop('Fwd IAT Max', axis=1)
df = df.drop('Destination Port', axis=1)
df = df.drop('Packet Length Std', axis=1)
df = df.drop('Flow Duration', axis=1)
df = df.drop('Total Backward Packets', axis=1)
df = df.drop('Total Length of Fwd Packets', axis=1)
df = df.drop('Fwd Packet Length Min', axis=1)
df = df.drop('Bwd Packet Length Max', axis=1)
df = df.drop('Flow Packets/s', axis=1)
df = df.drop('Flow IAT Mean', axis=1)
df = df.drop('Flow IAT Min', axis=1)
df = df.drop('Fwd IAT Total', axis=1)
df = df.drop('Fwd IAT Min', axis=1)
df = df.drop('min_seg_size_forward', axis=1)
df = df.drop('Active Mean', axis=1)
df = df.drop('Active Min', axis=1)
df = df.drop('Total Length of Bwd Packets', axis=1)
df = df.drop('Total Fwd Packets', axis=1)
df = df.drop('Fwd Packet Length Mean', axis=1)
df = df.drop('Bwd Packet Length Mean', axis=1)
df = df.drop('Bwd Packet Length Std', axis=1)
df = df.drop('Flow IAT Std', axis=1)
df = df.drop('Fwd IAT Std', axis=1)
df = df.drop('Bwd IAT Mean', axis=1)
df = df.drop('Bwd IAT Std', axis=1)
df = df.drop('Bwd IAT Max', axis=1)
df = df.drop('Fwd PSH Flags', axis=1)
df = df.drop('Bwd PSH Flags', axis=1)
df = df.drop('Fwd URG Flags', axis=1)
df = df.drop('Bwd URG Flags', axis=1)
df = df.drop('Packet Length Mean', axis=1)
df = df.drop('FIN Flag Count', axis=1)
df = df.drop('RST Flag Count', axis=1)
df = df.drop('PSH Flag Count', axis=1)
df = df.drop('ECE Flag Count', axis=1)
df = df.drop('Average Packet Size', axis=1)
df = df.drop('Avg Fwd Segment Size', axis=1)
df = df.drop('Avg Bwd Segment Size', axis=1)
df = df.drop('Idle Mean', axis=1)
df = df.drop('Idle Max', axis=1)
df = df.drop('Idle Min', axis=1)


df.to_csv('New folder/processed-dataset/cicdos2019-multi-test-pr.csv', index=False)

print(datetime.now()-start)